"""OpenAPI models: `*Req` request bodies and `*RespResult` HTTP results."""

from ecommerce_genie_ontology.common.dtos.ontology import (
    DpReq,
    DpRespResult,
    HlReq,
    HlRespResult,
    LsReq,
    LsRespResult,
    PwReq,
    PwRespResult,
    DyReq,
    DyRespResult,
    TcReq,
    TcRespResult,
    WfItemResult,
    WfReq,
    WfRespResult,
    WhReq,
    WhRespResult,
)

__all__ = [
    "DpReq",
    "DpRespResult",
    "HlReq",
    "HlRespResult",
    "LsReq",
    "LsRespResult",
    "PwReq",
    "PwRespResult",
    "DyReq",
    "DyRespResult",
    "TcReq",
    "TcRespResult",
    "WfItemResult",
    "WfReq",
    "WfRespResult",
    "WhReq",
    "WhRespResult",
]
