from __future__ import annotations

from typing import Any, Protocol


class GenieFacade(Protocol):
    def upsert_agent(self, serialized_space: str, description: str) -> str: ...

    def certify_and_tag_agent(self, space_id: str) -> None: ...

    def write_registry(self, space_id: str) -> None: ...

    def resolve_space_id(self) -> str: ...

    def ask(self, question: str) -> None: ...

    def trash_agent(self) -> None: ...
