from __future__ import annotations

from typing import Protocol

from ecommerce_genie_ontology.common.dtos.jobs import JobSpec
from ecommerce_genie_ontology.common.dtos.ontology import DpCtx, DyCtx, LsCtx, PwCtx, TcCtx, WfCtx, WhCtx
from ecommerce_genie_ontology.common.dtos.pipeline import EcCtx, EhCtx, EmCtx, FcCtx, NxCtx, OdCtx, OhCtx


class WorkflowTask(Protocol):
    key: str

    def run(self, ctx: WfCtx) -> None: ...


class Workflow(Protocol):
    name: str

    def run(self, ctx: WfCtx) -> None: ...


class WorkflowRunner(Protocol):
    def run(self, ctx: WfCtx) -> None: ...

    def deploy(self, ctx: DpCtx) -> None: ...

    def trigger(self, ctx: WfCtx) -> None: ...

    def list_workflows(self, ctx: LsCtx) -> None: ...

    def provision_workspace(self, ctx: PwCtx) -> None: ...

    def provision_warehouse(self, ctx: WhCtx) -> None: ...

    def publish_mcp(self) -> None: ...

    def publish_domains(self) -> None: ...

    def truncate(self, ctx: TcCtx) -> None: ...

    def destroy(self, ctx: DyCtx) -> None: ...

    def generate_historical(self, ctx: OhCtx) -> None: ...

    def generate_realtime(self, ctx: OdCtx) -> None: ...

    def etl_historical(self, ctx: EhCtx) -> None: ...

    def generate_next_oltp(self, ctx: NxCtx) -> None: ...

    def etl_cdc(self, ctx: EcCtx) -> None: ...

    def etl_next_months(self, ctx: EmCtx) -> None: ...

    def run_fraud_case(self, ctx: FcCtx) -> None: ...

    def job_specs(self) -> list[JobSpec]: ...
