name: 02 - Fraud Agent - 02 - Fraud Address Link Agent

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create:
    uses: ./.github/workflows/databricks-create-one-genie-agent.yml
    with:
      agent_id: address_link
      agent_title: Fraud Address Link Agent
    secrets: inherit
