name: 02 - Fraud Agent - 05 - Fraud First-Order Agent

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create:
    uses: ./.github/workflows/databricks-create-one-genie-agent.yml
    with:
      agent_id: first_order
      agent_title: Fraud First-Order Agent
    secrets: inherit
