name: 02 - Fraud Agent - 03 - Fraud Ship-to Bill-to Agent

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create:
    uses: ./.github/workflows/databricks-create-one-genie-agent.yml
    with:
      agent_id: ship_bill
      agent_title: Fraud Ship-to Bill-to Agent
    secrets: inherit
