name: 02 - Fraud Agent - 01 - Fraud Velocity Agent

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create:
    uses: ./.github/workflows/databricks-create-one-genie-agent.yml
    with:
      agent_id: velocity
      agent_title: Fraud Velocity Agent
    secrets: inherit
