name: 02 - Fraud Agent - 07 - Fraud Promo Agent

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create:
    uses: ./.github/workflows/databricks-create-one-genie-agent.yml
    with:
      agent_id: promo
      agent_title: Fraud Promo Agent
    secrets: inherit
